version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - frontend/package.json
    - frontend/package-lock.json
    - 'frontend/build/**/*'
  discard-paths: yes
